version: '3'
services:
  redis:
    image: redis
  worker:
    env_file: .envrc
    image: weather:latest
    command: python worker.py
    depends_on:
      - redis
  web:
    env_file: .envrc
    image: weather:latest
    command: python app.py
    ports:
      - "5003:80"
    depends_on:
      - redis
